//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopulationModels.UI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PopulationModels.UI.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ModelParameters {
            get {
                return ResourceManager.GetString("ModelParameters", resourceCulture);
            }
        }
        
        public static string InitialValues {
            get {
                return ResourceManager.GetString("InitialValues", resourceCulture);
            }
        }
        
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string TimeStep {
            get {
                return ResourceManager.GetString("TimeStep", resourceCulture);
            }
        }
        
        public static string MaxTime {
            get {
                return ResourceManager.GetString("MaxTime", resourceCulture);
            }
        }
        
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        public static string Bazykin {
            get {
                return ResourceManager.GetString("Bazykin", resourceCulture);
            }
        }
        
        public static string BazykinModel {
            get {
                return ResourceManager.GetString("BazykinModel", resourceCulture);
            }
        }
        
        public static string Sunlight {
            get {
                return ResourceManager.GetString("Sunlight", resourceCulture);
            }
        }
        
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        public static string Prey {
            get {
                return ResourceManager.GetString("Prey", resourceCulture);
            }
        }
        
        public static string Predators {
            get {
                return ResourceManager.GetString("Predators", resourceCulture);
            }
        }
        
        public static string InitialPrey {
            get {
                return ResourceManager.GetString("InitialPrey", resourceCulture);
            }
        }
        
        public static string InitialPredator {
            get {
                return ResourceManager.GetString("InitialPredator", resourceCulture);
            }
        }
        
        public static string InitialResource {
            get {
                return ResourceManager.GetString("InitialResource", resourceCulture);
            }
        }
        
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        public static string Bazykin_A {
            get {
                return ResourceManager.GetString("Bazykin_A", resourceCulture);
            }
        }
        
        public static string Bazykin_B {
            get {
                return ResourceManager.GetString("Bazykin_B", resourceCulture);
            }
        }
        
        public static string Bazykin_C {
            get {
                return ResourceManager.GetString("Bazykin_C", resourceCulture);
            }
        }
        
        public static string Bazykin_D {
            get {
                return ResourceManager.GetString("Bazykin_D", resourceCulture);
            }
        }
        
        public static string Bazykin_E {
            get {
                return ResourceManager.GetString("Bazykin_E", resourceCulture);
            }
        }
        
        public static string Bazykin_M {
            get {
                return ResourceManager.GetString("Bazykin_M", resourceCulture);
            }
        }
        
        public static string Bazykin_P {
            get {
                return ResourceManager.GetString("Bazykin_P", resourceCulture);
            }
        }
        
        public static string TimePeriod {
            get {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }
        
        public static string Bazykin_R {
            get {
                return ResourceManager.GetString("Bazykin_R", resourceCulture);
            }
        }
        
        public static string BazykinModelSmall {
            get {
                return ResourceManager.GetString("BazykinModelSmall", resourceCulture);
            }
        }
        
        public static string BazykinModelSunlight {
            get {
                return ResourceManager.GetString("BazykinModelSunlight", resourceCulture);
            }
        }
        
        public static string LotkaVolterraModel {
            get {
                return ResourceManager.GetString("LotkaVolterraModel", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        public static string Bazykin_A_increase {
            get {
                return ResourceManager.GetString("Bazykin_A_increase", resourceCulture);
            }
        }
        
        public static string Bazykin_B_increase {
            get {
                return ResourceManager.GetString("Bazykin_B_increase", resourceCulture);
            }
        }
        
        public static string Bazykin_A_decrease {
            get {
                return ResourceManager.GetString("Bazykin_A_decrease", resourceCulture);
            }
        }
        
        public static string Bazykin_D_increase {
            get {
                return ResourceManager.GetString("Bazykin_D_increase", resourceCulture);
            }
        }
        
        public static string Bazykin_D_decrease {
            get {
                return ResourceManager.GetString("Bazykin_D_decrease", resourceCulture);
            }
        }
        
        public static string Bazykin_B_decrease {
            get {
                return ResourceManager.GetString("Bazykin_B_decrease", resourceCulture);
            }
        }
        
        public static string Bazykin_C_increase {
            get {
                return ResourceManager.GetString("Bazykin_C_increase", resourceCulture);
            }
        }
        
        public static string Bazykin_C_decrease {
            get {
                return ResourceManager.GetString("Bazykin_C_decrease", resourceCulture);
            }
        }
        
        public static string Bazykin_E_increase {
            get {
                return ResourceManager.GetString("Bazykin_E_increase", resourceCulture);
            }
        }
        
        public static string Bazykin_E_decrease {
            get {
                return ResourceManager.GetString("Bazykin_E_decrease", resourceCulture);
            }
        }
        
        public static string Bazykin_A_zero {
            get {
                return ResourceManager.GetString("Bazykin_A_zero", resourceCulture);
            }
        }
        
        public static string Bazykin_B_zero {
            get {
                return ResourceManager.GetString("Bazykin_B_zero", resourceCulture);
            }
        }
        
        public static string Bazykin_C_zero {
            get {
                return ResourceManager.GetString("Bazykin_C_zero", resourceCulture);
            }
        }
        
        public static string Bazykin_D_zero {
            get {
                return ResourceManager.GetString("Bazykin_D_zero", resourceCulture);
            }
        }
        
        public static string Bazykin_E_zero {
            get {
                return ResourceManager.GetString("Bazykin_E_zero", resourceCulture);
            }
        }
        
        public static string Bazykin_P_increase {
            get {
                return ResourceManager.GetString("Bazykin_P_increase", resourceCulture);
            }
        }
        
        public static string Bazykin_P_decrease {
            get {
                return ResourceManager.GetString("Bazykin_P_decrease", resourceCulture);
            }
        }
        
        public static string Bazykin_P_zero {
            get {
                return ResourceManager.GetString("Bazykin_P_zero", resourceCulture);
            }
        }
        
        public static string BazykinModel_description {
            get {
                return ResourceManager.GetString("BazykinModel_description", resourceCulture);
            }
        }
        
        public static string OdeParameters {
            get {
                return ResourceManager.GetString("OdeParameters", resourceCulture);
            }
        }
        
        public static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string PlotType_time {
            get {
                return ResourceManager.GetString("PlotType_time", resourceCulture);
            }
        }
        
        public static string PlotType_phase {
            get {
                return ResourceManager.GetString("PlotType_phase", resourceCulture);
            }
        }
        
        public static string PlotType_phase_description {
            get {
                return ResourceManager.GetString("PlotType_phase_description", resourceCulture);
            }
        }
        
        public static string PlotType_time_description {
            get {
                return ResourceManager.GetString("PlotType_time_description", resourceCulture);
            }
        }
        
        public static string PlotType_phase_smalScatter {
            get {
                return ResourceManager.GetString("PlotType_phase_smalScatter", resourceCulture);
            }
        }
        
        public static string PlotType_phase_largeScatter {
            get {
                return ResourceManager.GetString("PlotType_phase_largeScatter", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        public static string About_title {
            get {
                return ResourceManager.GetString("About_title", resourceCulture);
            }
        }
        
        public static string About_text {
            get {
                return ResourceManager.GetString("About_text", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string About_author {
            get {
                return ResourceManager.GetString("About_author", resourceCulture);
            }
        }
        
        public static string About_sources {
            get {
                return ResourceManager.GetString("About_sources", resourceCulture);
            }
        }
    }
}
